'use client';

import { useCallback, useEffect, useState } from 'react';
import { readJsonResponse } from '@/lib/client-response';

type Job = { id: string; type: string; status: string; attempts: number; maxAttempts: number; lastError?: string | null; createdAt: string };

export default function BackgroundJobQueue() {
  const [items, setItems] = useState<Job[]>([]); const [status, setStatus] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/admin/jobs?status=${status}&page=1&pageSize=25`, { cache: 'no-store' }); const body = await readJsonResponse<{ items?: Job[]; error?: string }>(response, 'Unable to load jobs'); if (!response.ok) throw new Error(body.error); setItems(body.items || []); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load jobs'); } finally { setLoading(false); } }, [status]);
  useEffect(() => { void load(); }, [load]);
  const act = async (id: string, action: 'retry' | 'dismiss') => { const response = await fetch('/api/admin/jobs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, action }) }); if (response.ok) await load(); else setError((await readJsonResponse<{ error?: string }>(response, 'Unable to update job')).error || 'Unable to update job'); };
  return <section className="space-y-4 rounded-xl border border-zinc-800 bg-zinc-900 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">Background jobs</h3><p className="text-sm text-zinc-500">Retries, dead letters, and webhook reconciliation. Admin access only.</p></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-white"><option value="all">All states</option><option value="pending">Pending</option><option value="processing">Processing</option><option value="dead_letter">Dead letter</option><option value="completed">Completed</option></select></div>{error && <div className="rounded-lg border border-red-800 bg-red-950/40 p-3 text-sm text-red-300">{error}<button onClick={() => void load()} className="ml-3 underline">Retry load</button></div>}{loading && !items.length ? <p className="text-sm text-zinc-500">Loading jobs…</p> : !items.length ? <p className="rounded-xl border border-dashed border-zinc-700 p-6 text-center text-sm text-zinc-500">No jobs in this state.</p> : <div className="space-y-2">{items.map((job) => <article key={job.id} className="flex flex-col justify-between gap-3 rounded-xl border border-zinc-800 bg-zinc-950 p-4 sm:flex-row sm:items-center"><div className="min-w-0"><p className="truncate font-mono text-sm text-white">{job.type}</p><p className="text-xs text-zinc-500">{job.status} · attempt {job.attempts}/{job.maxAttempts} · {new Date(job.createdAt).toLocaleString()}</p>{job.lastError && <p className="mt-1 line-clamp-2 text-xs text-red-300">{job.lastError}</p>}</div>{['pending', 'dead_letter', 'processing'].includes(job.status) && <div className="flex gap-2"><button onClick={() => void act(job.id, 'retry')} className="rounded-lg bg-yellow-300 px-3 py-2 text-xs font-semibold text-black">Retry</button><button onClick={() => void act(job.id, 'dismiss')} className="rounded-lg border border-zinc-700 px-3 py-2 text-xs text-zinc-300">Dismiss</button></div>}</article>)}</div>}</section>;
}
